import * as React from 'react';
import Box from '@mui/material/Box';
import Typography from '@mui/material/Typography';
import LayoutCheckout from 'dh-marvel/components/layouts/layout-checkout';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardMedia from '@mui/material/CardMedia';
import { styled } from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import useOrder from 'context/useOrden';
import { setSnackbar } from 'context/action';
import { useEffect } from 'react';
import Snackbar from '@mui/material/Snackbar';
import Alert from '@mui/material/Alert';
import StepperForm from 'dh-marvel/components/StepperForm';
import Head from 'next/head';
import BodySingle from 'dh-marvel/components/layouts/body/single/body-single';


const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: 'center',
    color: theme.palette.text.secondary,
}));




const Checkout: NextPage = () => {

    const router = useRouter();
    const { state: { order: { comic: { title, img, price } } }, state: { snackbar: { open, message } }, dispatch } = useOrder();
    console.log(title)


    const handleClose = () => {
        setSnackbar(dispatch, "")
    }

     useEffect(() => {
        if (title === "")
            router.push("/")
    }, [])
 

    return (
     <LayoutCheckout>
            <Head>
                <title>Checkout</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BodySingle title={title}>
                    <Box sx={{ flexGrow: 1 }}>
                <Grid container spacing={2}>
                    <Grid item xs={8}>
                        <Box sx={{ width: '100%' }}>
                           <StepperForm />
                        </Box>
                    </Grid>
            
                    <Grid item xs={4}>
                        <Item>
                            <Card >
                                <CardMedia
                                    component="img"
                                    height="250"
                                    image={img}
                                    alt={title}

                                />
                                <CardContent>
                                    <Typography variant="h6" component="div">
                                    {title}
                                    </Typography>
                                    <Typography variant="body1">
                                    TOTAL = ${price}
                                    </Typography>
                                    
                                </CardContent>
                            </Card>
                        </Item>
                    </Grid>

                </Grid>
                <Snackbar
                    open={open}
                    autoHideDuration={6000}
                    onClose={handleClose}
                >
                    <Alert severity='error'>{message}</Alert>
                </Snackbar>
            </Box>
            </BodySingle>
        
        
     </LayoutCheckout>
    );
}


export default Checkout;



