import type {NextPage} from 'next'
import Head from 'next/head'
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import GridMarvel from 'dh-marvel/components/grid-marvel';





const Index: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <BodySingle title={"Sample"}>
                <h1>hola</h1>
            <GridMarvel />
            
            </BodySingle>
        </>
    )
}

export default Index
